/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Role.AssetAgentRole;
import Business.Role.AssetMarketAdminRole;
import Business.Role.CompanyAgentRole;
import Business.Role.CryptoAgentRole;
import Business.Role.CryptoMarketAdminRole;
import Business.Role.CustomerRole;
import Business.Role.ForexAgentRole;
import Business.Role.ForexMarketAdminRole;
import Business.Role.MutualFundsAgentRole;
import Business.Role.Role;
import Business.Role.StockMarketAdminRole;
import Business.Role.SystemAdminRole;
import Business.SendEmail;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;

/**
 *
 * @author prathameshnemade
 */
public class AccountCreateJPanel_1 extends javax.swing.JPanel {

    EcoSystem system;
    UserAccount account;

    /**
     * Creates new form AccountCreateJPanel
     */
    public AccountCreateJPanel_1(EcoSystem system, UserAccount account) {
        this.system = system;
        this.account = account;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginJButton = new javax.swing.JButton();
        emailIDJField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JPasswordField = new javax.swing.JPasswordField();
        confirmJPasswordField = new javax.swing.JPasswordField();
        roleComboBox = new javax.swing.JComboBox<>();
        brandJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        loginJButton.setBackground(new java.awt.Color(200, 203, 178));
        loginJButton.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        loginJButton.setForeground(new java.awt.Color(67, 100, 100));
        loginJButton.setText("Register");
        loginJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginJButtonActionPerformed(evt);
            }
        });

        emailIDJField.setBackground(new java.awt.Color(238, 238, 238));
        emailIDJField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        emailIDJField.setText("Enter email id");
        emailIDJField.setToolTipText("Click to enter your Email ID.");
        emailIDJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        emailIDJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailIDJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailIDJFieldFocusLost(evt);
            }
        });
        emailIDJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIDJFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER");

        JPasswordField.setBackground(new java.awt.Color(238, 238, 238));
        JPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        confirmJPasswordField.setBackground(new java.awt.Color(238, 238, 238));
        confirmJPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        roleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stock Market Admin", "Asset Market Admin", "Crypto Market Admin", "Forex Market Admin", "Asset Agent", "Company Agent", "Crypto Agent", "Forex Agent", "Mutual Funds Agent", "Customer", "System Admin", " " }));
        roleComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                roleComboBoxItemStateChanged(evt);
            }
        });
        roleComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                roleComboBoxFocusGained(evt);
            }
        });
        roleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboBoxActionPerformed(evt);
            }
        });
        roleComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                roleComboBoxPropertyChange(evt);
            }
        });

        brandJLabel.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        brandJLabel.setForeground(new java.awt.Color(67, 100, 100));
        brandJLabel.setText("Role (*):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(loginJButton)
                    .addComponent(emailIDJField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                    .addComponent(JPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(brandJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(193, 193, 193)
                .addComponent(emailIDJField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmJPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String validateregister() {
        String isValid = "";

        if (!this.emailIDJField.getText().matches("[a-zA-Z0-9]+[._a-zA-Z0-9!#$%&'*+-/=?^_`{|}~]*[a-zA-Z]*@[a-zA-Z0-9]{2,8}.[a-zA-Z.]{2,6}")) {
            isValid += "Invalid Email Id! Should be minimum 8 and maximum 20 characters! \n";
        }
        if (!new String(this.JPasswordField.getPassword()).matches("[a-zA-Z0-9@#$%]{8,20}")) {
            isValid += "Invalid Password! Should be minimum 8 and maximum 20 characters! \n";
        }
        if (!new String(this.confirmJPasswordField.getPassword()).equals(new String(this.JPasswordField.getPassword()))) {
            isValid += "Confirm Password should be same as Password! \n";
        }
        if (!this.system.getUserAccountDirectory().checkIfUsernameIsUnique(this.emailIDJField.getText())) {
            isValid += "Username already used! \n";
        }
        return isValid;
    }

    private void loginJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginJButtonActionPerformed
        String isValid = this.validateregister();
        if (isValid.equals("")) {
            if (emailIDJField != null && JPasswordField.getPassword() != null) {
                String password = new String(JPasswordField.getPassword());
                String confirmPassword = new String(confirmJPasswordField.getPassword());
                System.out.println("JPasswordField.getPassword().toString()" + password);
                System.out.println("confirmJPasswordField.getPassword().toString()" + this.emailIDJField.getText());
                if (password.equals(confirmPassword)) {
                    if (this.system.getUserAccountDirectory().checkIfUsernameIsUnique(this.emailIDJField.getText())) {
                        Role role;
                        Employee employee = new Employee();
                        employee.setName(this.emailIDJField.getText());
                        String value = this.roleComboBox.getSelectedItem().toString();
                        if (value == "Stock Market Admin") {
                            role = new StockMarketAdminRole();
                        } else if (value == "Asset Market Admin") {
                            role = new AssetMarketAdminRole();
                        } else if (value == "Crypto Market Admin") {
                            role = new CryptoMarketAdminRole();
                        } else if (value == "Forex Market Admin") {
                            role = new ForexMarketAdminRole();
                        } else if (value == "Asset Agent") {
                            role = new AssetAgentRole();
                        } else if (value == "Company Agent") {
                            role = new CompanyAgentRole();
                        } else if (value == "Crypto Agent") {
                            role = new CryptoAgentRole();
                        } else if (value == "Forex Agent") {
                            role = new ForexAgentRole();
                        } else if (value == "Mutual Funds Agent") {
                            role = new MutualFundsAgentRole();
                        } else if (value == "System Admin") {
                            role = new SystemAdminRole();
                        } else {
                            role = new CustomerRole();
                        }
                        
                        SendEmail temp1 = new SendEmail("prathameshnemade95@gmail.com", "Welcome!!", "Hi " + this.emailIDJField.getText() + ", Your account was updated successfully for role " + value +" !");
                        temp1.sendMail();
                        this.system.getUserAccountDirectory().createUserAccount(this.emailIDJField.getText(), password, employee, role);
                        JOptionPane.showMessageDialog(this, "User registered successfully!!", "Register", INFORMATION_MESSAGE);
//                        this.emailIDJField.setText("Enter email id");
//                        this.JPasswordField.setText("");
//                        this.confirmJPasswordField.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "EmailId already used!!", "Register", ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Password and Confirm Password should match!", "Register", ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Username or Password requried.", "Register", ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, isValid, "Register", ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginJButtonActionPerformed

    private void emailIDJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIDJFieldFocusGained
        if (emailIDJField.getText().equals("Enter email id")) {
            emailIDJField.setText("");
        }
    }//GEN-LAST:event_emailIDJFieldFocusGained

    private void emailIDJFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailIDJFieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIDJFieldFocusLost

    private void emailIDJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIDJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIDJFieldActionPerformed

    private void roleComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_roleComboBoxItemStateChanged
        //TOdo
    }//GEN-LAST:event_roleComboBoxItemStateChanged

    private void roleComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_roleComboBoxFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxFocusGained

    private void roleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxActionPerformed

    private void roleComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_roleComboBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboBoxPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPasswordField;
    private javax.swing.JLabel brandJLabel;
    private javax.swing.JPasswordField confirmJPasswordField;
    private javax.swing.JTextField emailIDJField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginJButton;
    private javax.swing.JComboBox<String> roleComboBox;
    // End of variables declaration//GEN-END:variables
}
