/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.AssetMarketAdminRole;

import Business.EcoSystem;
import Business.Enterprise.AssetMarketEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.IndustriesOrganization;
import Business.Organization.JewelleryOrganization;
import Business.Organization.Organization;
import Business.Organization.RealEstateOrganization;
import Business.Role.AssetAgentRole;
import Business.UserAccount.UserAccount;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author prathameshnemade
 */
public class AssetIndustryCreateJPanel extends javax.swing.JPanel {

    EcoSystem ecosystem;
    UserAccount account;
    JSplitPane jSplitPane;
    JPanel browsingJPanel;
    UserAccount selectedUser;
    Network ongoinNetwork;

    ArrayList<UserAccount> assetsAdminUser = new ArrayList<>();

    public AssetIndustryCreateJPanel(EcoSystem ecosystem, UserAccount account, JSplitPane jSplitPane, JPanel browsingJPanel) {
        this.ecosystem = ecosystem;
        this.account = account;
        this.jSplitPane = jSplitPane;
        this.browsingJPanel = browsingJPanel;
        initComponents();

        for (int i = 0; i < this.ecosystem.getNetwork().getNetworkList().size(); i++) {
            Network ongoing1 = this.ecosystem.getNetwork().getNetworkList().get(i);
            if (ongoing1.getIsSelected()) {
                ongoinNetwork = ongoing1;
            }
        }
        this.industryDateOfCreationJLabel.setText(new Date().toString());
        setAssetAdminUsers();
    }

    public void setAssetAdminUsers() {
        ArrayList<String> asset = new ArrayList<>();
        for (int i = 0; i < this.ecosystem.getUserAccountDirectory().getUserAccountList().size(); i++) {
            UserAccount ongoing = this.ecosystem.getUserAccountDirectory().getUserAccountList().get(i);
            if (ongoing.getRole() instanceof AssetAgentRole) {
                Boolean found = false;
                for (int k = 0; k < this.ecosystem.getNetwork().getNetworkList().size(); k++) {
                    for (int j = 0; j < this.ecosystem.getNetwork().getNetworkList().get(k).getEnterpriseDirectory().getEnterpriseDir().size(); j++) {
                        Enterprise temp = this.ecosystem.getNetwork().getNetworkList().get(k).getEnterpriseDirectory().getEnterpriseDir().get(j);
                        if (temp instanceof AssetMarketEnterprise) {
                            for (int p = 0; p < temp.getOrganizationDirectory().getOrganizationList().size(); p++) {
                                Organization temp1 = temp.getOrganizationDirectory().getOrganizationList().get(p);
                                if (temp1 instanceof IndustriesOrganization) {
                                    IndustriesOrganization temp3 = ((IndustriesOrganization) temp1);
                                    if (temp3.getAdmin() == ongoing) {
                                        found = true;
                                    }
                                } else if (temp1 instanceof JewelleryOrganization) {
                                    JewelleryOrganization temp4 = ((JewelleryOrganization) temp1);
                                    if (temp4.getAdmin() == ongoing) {
                                        found = true;
                                    }

                                } else if (temp1 instanceof RealEstateOrganization) {
                                    RealEstateOrganization temp5 = ((RealEstateOrganization) temp1);
                                    if (temp5.getAdmin() == ongoing) {
                                        found = true;
                                    }

                                }
                            }
                        }
                    }
                }
                if (!found) {
                    this.assetsAdminUser.add(ongoing);
                    asset.add(ongoing.getUsername());
                }
            }
        }
        String[] assetSDropdown = asset.toArray(new String[asset.size()]);
        DefaultComboBoxModel<String> brandSDropdownModel = new DefaultComboBoxModel<>(assetSDropdown);
        this.industryComboBox.setModel(brandSDropdownModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        serialNoJLabel = new javax.swing.JLabel();
        industryNameJField = new javax.swing.JTextField();
        cardentifierJLabel1 = new javax.swing.JLabel();
        industryDateOfCreationJLabel = new javax.swing.JTextField();
        serialNoJLabel1 = new javax.swing.JLabel();
        industryUnitJField = new javax.swing.JTextField();
        serialNoJLabel2 = new javax.swing.JLabel();
        nameJField = new javax.swing.JTextField();
        serialNoJLabel3 = new javax.swing.JLabel();
        industryJField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        brandJLabel1 = new javax.swing.JLabel();
        industryComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        serialNoJLabel4 = new javax.swing.JLabel();
        industryLocationJField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        serialNoJLabel.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        serialNoJLabel.setForeground(new java.awt.Color(67, 100, 100));
        serialNoJLabel.setText("Company Name(*):");

        industryNameJField.setBackground(new java.awt.Color(238, 238, 238));
        industryNameJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        industryNameJField.setText("Enter here");
        industryNameJField.setToolTipText("Click to enter your name.");
        industryNameJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        industryNameJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industryNameJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                industryNameJFieldnameChangeHandler(evt);
            }
        });
        industryNameJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industryNameJFieldActionPerformed(evt);
            }
        });

        cardentifierJLabel1.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        cardentifierJLabel1.setForeground(new java.awt.Color(67, 100, 100));
        cardentifierJLabel1.setText("Date of Creation:");

        industryDateOfCreationJLabel.setEditable(false);
        industryDateOfCreationJLabel.setBackground(new java.awt.Color(216, 220, 228));
        industryDateOfCreationJLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        industryDateOfCreationJLabel.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        industryDateOfCreationJLabel.setToolTipText("This is your identifier.");
        industryDateOfCreationJLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        industryDateOfCreationJLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industryDateOfCreationJLabelActionPerformed(evt);
            }
        });

        serialNoJLabel1.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        serialNoJLabel1.setForeground(new java.awt.Color(67, 100, 100));
        serialNoJLabel1.setText("Unit(*):");

        industryUnitJField.setBackground(new java.awt.Color(238, 238, 238));
        industryUnitJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        industryUnitJField.setText("Enter here");
        industryUnitJField.setToolTipText("Click to enter your name.");
        industryUnitJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        industryUnitJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industryUnitJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                industryUnitJFieldnameChangeHandler(evt);
            }
        });
        industryUnitJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industryUnitJFieldActionPerformed(evt);
            }
        });

        serialNoJLabel2.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        serialNoJLabel2.setForeground(new java.awt.Color(67, 100, 100));
        serialNoJLabel2.setText("Name (*):");

        nameJField.setBackground(new java.awt.Color(238, 238, 238));
        nameJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameJField.setText("Enter here");
        nameJField.setToolTipText("Click to enter your name.");
        nameJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        nameJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameJFieldnameChangeHandler(evt);
            }
        });
        nameJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJFieldActionPerformed(evt);
            }
        });

        serialNoJLabel3.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        serialNoJLabel3.setForeground(new java.awt.Color(67, 100, 100));
        serialNoJLabel3.setText("Price(*):");

        industryJField.setBackground(new java.awt.Color(238, 238, 238));
        industryJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        industryJField.setText("Enter here");
        industryJField.setToolTipText("Click to enter your name.");
        industryJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        industryJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industryJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                industryJFieldnameChangeHandler(evt);
            }
        });
        industryJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industryJFieldActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(200, 203, 178));
        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(67, 100, 100));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        brandJLabel1.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        brandJLabel1.setForeground(new java.awt.Color(67, 100, 100));
        brandJLabel1.setText("Admin (*):");

        industryComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                industryComboBoxItemStateChanged(evt);
            }
        });
        industryComboBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industryComboBoxFocusGained(evt);
            }
        });
        industryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industryComboBoxActionPerformed(evt);
            }
        });
        industryComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                industryComboBoxPropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create a Industry");

        serialNoJLabel4.setFont(new java.awt.Font("PT Sans Caption", 0, 14)); // NOI18N
        serialNoJLabel4.setForeground(new java.awt.Color(67, 100, 100));
        serialNoJLabel4.setText("Location (*):");

        industryLocationJField.setBackground(new java.awt.Color(238, 238, 238));
        industryLocationJField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        industryLocationJField.setText("Enter here");
        industryLocationJField.setToolTipText("Click to enter your name.");
        industryLocationJField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 5));
        industryLocationJField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                industryLocationJFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                industryLocationJFieldnameChangeHandler(evt);
            }
        });
        industryLocationJField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                industryLocationJFieldMouseClicked(evt);
            }
        });
        industryLocationJField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industryLocationJFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serialNoJLabel)
                    .addComponent(brandJLabel1)
                    .addComponent(serialNoJLabel2)
                    .addComponent(serialNoJLabel4)
                    .addComponent(serialNoJLabel1)
                    .addComponent(serialNoJLabel3)
                    .addComponent(cardentifierJLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(industryDateOfCreationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(industryLocationJField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(industryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(industryNameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(industryUnitJField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(industryJField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(industryNameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNoJLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(industryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brandJLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNoJLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(industryLocationJField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serialNoJLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNoJLabel1)
                    .addComponent(industryUnitJField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialNoJLabel3)
                    .addComponent(industryJField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(industryDateOfCreationJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardentifierJLabel1))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void industryNameJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryNameJFieldFocusGained
        if (industryNameJField.getText().equals("Enter here")) {
            industryNameJField.setText("");
        }
    }//GEN-LAST:event_industryNameJFieldFocusGained

    private void industryNameJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryNameJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_industryNameJFieldnameChangeHandler

    private void industryNameJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industryNameJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industryNameJFieldActionPerformed

    private void industryDateOfCreationJLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industryDateOfCreationJLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industryDateOfCreationJLabelActionPerformed

    private void industryUnitJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryUnitJFieldFocusGained
        if (industryUnitJField.getText().equals("Enter here")) {
            industryUnitJField.setText("");
        }
    }//GEN-LAST:event_industryUnitJFieldFocusGained

    private void industryUnitJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryUnitJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_industryUnitJFieldnameChangeHandler

    private void industryUnitJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industryUnitJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industryUnitJFieldActionPerformed

    private void nameJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJFieldFocusGained
        if (this.nameJField.getText().equals("Enter here")) {
            nameJField.setText("");
        }
    }//GEN-LAST:event_nameJFieldFocusGained

    private void nameJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJFieldnameChangeHandler

    private void nameJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJFieldActionPerformed

    private void industryJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryJFieldFocusGained
        if (this.industryJField.getText().equals("Enter here")) {
            industryJField.setText("");
        }
    }//GEN-LAST:event_industryJFieldFocusGained

    private void industryJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_industryJFieldnameChangeHandler

    private void industryJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industryJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industryJFieldActionPerformed

    public Boolean validateItem() {
        String errorMEssage = "";
        if (this.industryComboBox.getSelectedItem() == null) {
            errorMEssage += "Select Admin to proceed! \n";
        }
        if (!this.industryNameJField.getText().matches("[a-zA-Z0-9]+")) {
            errorMEssage += "Invalid Company Name! \n";
        }
        if (!this.industryLocationJField.getText().matches("[a-zA-Z0-9]+")) {
            errorMEssage += "Invalid Location Name! \n";
        }

        if (!this.nameJField.getText().matches("[a-zA-Z]+")) {
            errorMEssage += "Invalid Name! \n";
        }
        if (!this.industryUnitJField.getText().matches("[0-9]+")) {
            errorMEssage += "Unit should be a number! \n";
        }
        if (!this.industryJField.getText().matches("[0-9]+")) {
            errorMEssage += "Price should be a number! \n";
        }
        if (errorMEssage.equals("")) {
            return true;
        }
        JOptionPane.showMessageDialog(this, errorMEssage, "Real Estate Edit", ERROR_MESSAGE);
        return false;
    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Boolean valid = validateItem();
        if (valid) {
            HashMap<String, HashMap<String, Object>> estates = new HashMap<>();
            HashMap<String, Object> estate = new HashMap<>();
            estate.put("maxPrice", this.industryJField.getText().toString());
            estate.put("quantity", this.industryUnitJField.getText().toString());
            estate.put("doc", new Date());
            estate.put("location", this.industryLocationJField.getText().toString());
            estates.put(this.nameJField.getText(), estate);

            for (int i = 0; i < ongoinNetwork.getEnterpriseDirectory().getEnterpriseDir().size(); i++) {
                Enterprise ongoing = ongoinNetwork.getEnterpriseDirectory().getEnterpriseDir().get(i);
                if (ongoing instanceof AssetMarketEnterprise) {
                    ongoing.getOrganizationDirectory().createIndustryOrganization(this.industryNameJField.getText(), Organization.Type.RealEstate, this.nameJField.getText().toString(), this.selectedUser, estates, new Date());
                }
            }
            setAssetAdminUsers();
            JOptionPane.showMessageDialog(this, "Industry created successfully!", "Industry", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void industryComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_industryComboBoxItemStateChanged
        _adminChnageHandler();
    }//GEN-LAST:event_industryComboBoxItemStateChanged

    public void _adminChnageHandler() {
        Integer selectedDelIndex = this.industryComboBox.getSelectedIndex();
        if (selectedDelIndex != -1) {
            this.selectedUser = this.assetsAdminUser.get(selectedDelIndex);
            System.out.println("!!!" + selectedUser.getUsername().toString());
        }
    }

    private void industryComboBoxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryComboBoxFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_industryComboBoxFocusGained

    private void industryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industryComboBoxActionPerformed

    private void industryComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_industryComboBoxPropertyChange
        this._adminChnageHandler();
    }//GEN-LAST:event_industryComboBoxPropertyChange

    private void industryLocationJFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryLocationJFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_industryLocationJFieldFocusGained

    private void industryLocationJFieldnameChangeHandler(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_industryLocationJFieldnameChangeHandler
        // TODO add your handling code here:
    }//GEN-LAST:event_industryLocationJFieldnameChangeHandler

    private void industryLocationJFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industryLocationJFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_industryLocationJFieldActionPerformed

    private void industryLocationJFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_industryLocationJFieldMouseClicked
        if (this.industryLocationJField.getText().equals("Enter here")) {
            industryLocationJField.setText("");
        }
    }//GEN-LAST:event_industryLocationJFieldMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel brandJLabel1;
    private javax.swing.JLabel cardentifierJLabel1;
    private javax.swing.JComboBox<String> industryComboBox;
    private javax.swing.JTextField industryDateOfCreationJLabel;
    private javax.swing.JTextField industryJField;
    private javax.swing.JTextField industryLocationJField;
    private javax.swing.JTextField industryNameJField;
    private javax.swing.JTextField industryUnitJField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameJField;
    private javax.swing.JLabel serialNoJLabel;
    private javax.swing.JLabel serialNoJLabel1;
    private javax.swing.JLabel serialNoJLabel2;
    private javax.swing.JLabel serialNoJLabel3;
    private javax.swing.JLabel serialNoJLabel4;
    // End of variables declaration//GEN-END:variables
}
